# Generated by Django 5.1.1 on 2024-09-27 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'contacts', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterField(
            model_name='contacts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 18, 41, 32, 58313)),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
